version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_USER: paris_data
      MYSQL_PASSWORD: paris_data
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: paris_data